# Waypoints describe the desired motion trajectory:
#  - time [s]: can be either a single value or an interval for which all the specified joint_positions hold
#  - joint_positions: a list of namespaces which contain the vector of joint position references of the relative device
#                     (the measurement units depend on the device type, e.g. qbhand needs a single [0,1] value).
#                     If a namespace is not specified for a given waypoint, it is assumed that it does not change the
#                     device position, e.g. if the end-effector pose remains unchanged for duration of the grasp, the
#                     user can avoid copy-pasting it for the involved waypoints. Nonetheless for critical applications
#                     it is recommended to specify it to avoid interpolation approximation, e.g. following the above
#                     example, the arm could start moving before the grasp has ended if the end-effector pose is not
#                     specified for all the waypoints.
#  - joint_velocities: optional, use it only if you want a nonzero values
#  - joint_accelerations: optional, use it only if you want a nonzero values
#
# It is worth noting that, if specified, joint_velocities and joint_accelerations must be of the same size of the
# relative joint_positions.

waypoints:
  -
    time: [2.0]
    joint_positions:
      cube1: [0.0, 0.5]
      cube2: [-1.0, 0.5]
      cube3: [-1.0, 0.5]
      cube4: [0.0, 0.5]
  -
    time: [4.0]
    joint_positions:
      cube1: [-1.0, 0.5]
      cube2: [-1.5, 0.5]
      cube3: [-1.5, 0.5]
      cube4: [0.0, 0.5]
  -
    time: [4.5]
    joint_positions:
      cube1: [-1.0, 0.5]
      cube2: [-1.5, 0.5]
      cube3: [-1.5, 0.5]
      cube4: [1.0, 0.5]
  -
    time: [5.0]
    joint_positions:
      cube1: [-1.0, 0.5]
      cube2: [-1.5, 0.5]
      cube3: [-1.5, 0.5]
      cube4: [0.0, 0.5]
  -
    time: [7.0]
    joint_positions:
      cube1: [0.0, 0.5]
      cube2: [-1.0, 0.5]
      cube3: [-1.0, 0.5]
      cube4: [0.0, 0.5]
  -
    time: [9.0]
    joint_positions:
      cube1: [1.0, 0.5]
      cube2: [-1.5, 0.5]
      cube3: [-1.5, 0.5]
      cube4: [0.0, 0.5]
  -
    time: [9.5]
    joint_positions:
      cube1: [1.0, 0.5]
      cube2: [-1.5, 0.5]
      cube3: [-1.5, 0.5]
      cube4: [1.0, 0.5]
  -
    time: [10.0]
    joint_positions:
      cube1: [1.0, 0.5]
      cube2: [-1.5, 0.5]
      cube3: [-1.5, 0.5]
      cube4: [0.0, 0.5]